font_family         SourceCodePro
font_size 14

copy_on_select      yes
select_by_word_characters @-./_~?&=%+#
detect_urls         yes


### tab_bar_style [ fade,slant,separator,powerline,custom,hidden ] ###
#tab_bar_style fade
#tab_fade 0.25 0.5 0.75 1

tab_bar_style powerline
#tab_powerline_style [ angled,salnted,round ]
tab_powerline_style angled


# BEGIN_KITTY_THEME
# Tomorrow Night
include current-theme.conf
# END_KITTY_THEME