preload = /home/chenyueren/.config/wallpaper/guts_office1.png
preload = /home/chenyueren/.config/wallpaper/guts_office2.jpg
preload = /home/chenyueren/.config/wallpaper/guts_office3.jpg
wallpaper = HDMI-A-1,/home/chenyueren/.config/wallpaper/guts_office1.png
wallpaper = DP-2,/home/chenyueren/.config/wallpaper/guts_office2.jpg
wallpaper = HDMI-A-2,/home/chenyueren/.config/wallpaper/guts_office3.jpg
